### ISSUE TITLE
Using static compress for css with python pkg instead of npm/lessc?

### ISSUE THREAD

**Issue by aardvark82** [alanhamlett/flask-static-compress#2]
Hi,
- is there a way to do css compress with? I don't have node installed and prefer pure python to simplify the deployment workflows. js minification works beautifully but css doesn't.

- are there available classes for js uglification, not only minification? e.g. replace variable names with a single letter, etc.... e.g. https://github.com/mishoo/UglifyJS2   again, a python pkg preferred over js bindings.

**Comment by alanhamlett** [comment]
There are too many Python CSS minify libraries to list here, any one will work. Use them with a custom compressor following these instructions:
https://github.com/jaysonsantos/jinja-assets-compressor#custom-compressors
