### ISSUE TITLE
FlaskStaticCompress changing cache policy?

### ISSUE THREAD

**Issue by aardvark82** [alanhamlett/flask-static-compress#3]
See link below - when calling FlaskStaticCompress(app) it seems to prevent Chrome or Safari from reloading changes made to a Jinja template. This is regardless of setting 
FlaskStaticCompress.COMPRESSOR_ENABLED = False

See Attached video - are there any Cache headers or other parameters being changed that could create this behaviour? 

See attached video link- using Pycharm and Chrome (I'm hitting shift-reload between each changes, out of screen recording area). 

https://www.dropbox.com/s/vfusvade44i2swt/Flask-Compress%20Bug.mov?dl=0

**Comment by alanhamlett** [comment]
Flask-Static-Compress doesn't control HTML caching, try disabling caching in your browser:
https://stackoverflow.com/a/7000899/1290627

**Comment by aardvark82** [comment]
Hi Alan - I'm well aware of the caching settings and have them disabled. 
The video shows how just enabling Flask-Static-Compress creates a caching/refreshing issue in development. 
Any further comments? I have the extension disabled right now as it creates too much of a change in workflow. I'll make more precise timings and investigations when I find time.

**Comment by alanhamlett** [comment]
The only part that Flask-Static-Compress deals with is stuff inside `{% compress %}{% endcompress %}` blocks, so that HTML is probably from Flask's dev server not detecting changes or not reloading when files change.
